# Extract the 'host' line from rustc version info

prepare:
  #!/usr/bin/env bash
  mkdir -p ./binaries
  cp ../result/bin/todou ./binaries/todou-{{`rustc -vV | grep 'host:' | cut -d' ' -f2`}}

# Build or Dev
dev:
    cargo run

# Helper to clear old sidecars
clean:
    rm -rf binaries
