
target_triple := `rustc -vV | grep 'host:' | cut -d' ' -f2`

prepare:
    #!/usr/bin/env bash
    mkdir -p ./binaries
    ln -sf ../../result/bin/todou "./binaries/todou-{{target_triple}}"
    echo "Sidecar prepared: todou-{{target_triple}}"

# Build or Dev
dev:
    cargo run

# Helper to clear old sidecars
clean:
    rm -rf binaries
